export const products = [
  {
    id: 1,
    name: "Ojotas",
    alt: "Foto de calzado",
    img: ["/Ojota1.jpeg", "/Ojota3.jpeg"],
    color: "Negro",
    price: 5200,
    stock: 1,
  },
  {
    id: 2,
    name: "Ojotas",
    alt: "Foto de calzado",
    img: "/Ojota2.jpeg",
    color: "Azul",
    price: 5200,
    stock: 1,
  },
  {
    id: 3,
    name: "Ojotas",
    alt: "Foto de calzado",
    img: "/Ojota4.jpeg",
    color: "Violeta",
    price: 5200,
    stock: 1,
  },
  {
    id: 4,
    name: "Zapatillas",
    alt: "Foto de calzado",
    img: "/Ojota5.jpeg",
    color: "Mostaza",
    price: 7900,
    stock: 1,
  },
  {
    id: 5,
    name: "Ojotas",
    alt: "Foto de calzado",
    img: "/Ojota6.jpeg",
    color: "Negro",
    price: 5200,
    stock: 1,
  },
  {
    id: 6,
    name: "Ojotas",
    alt: "Foto de calzado",
    img: "/Ojota7.jpeg",
    color: "Negro",
    price: 5200,
    stock: 1,
  },
  {
    id: 7,
    name: "Ojotas",
    alt: "Foto de calzado",
    img: "/Ojota8.jpeg",
    color: "Negro",
    price: 7900,
    stock: 1
  },
  {
    id: 8,
    name: "Ojotas",
    alt: "Foto de calzado",
    img: "/Ojota9.jpeg",
    color: "Negro",
    price: 5200,
    stock: 1,
  },
  {
    id: 9,
    name: "Ojotas",
    alt: "Foto de calzado",
    img: "/Ojota10.jpeg",
    color: "Negro",
    price: 5200,
    stock: 1,
  },
  {
    id: 10,
    name: "Ojotas",
    alt: "Foto de calzado",
    img: "/Ojota11.jpeg",
    color: "Negro",
    price: 7900,
    stock: 1,
  },
  {
    id: 11,
    name: "Ojotas",
    alt: "Foto de calzado",
    img: "/Ojota12.jpeg",
    color: "Blanco",
    price: 5200,
    stock: 1,
  },
  {
    id: 12,
    name: "Ojotas",
    alt: "Foto de calzado",
    img: "/Ojota13.jpeg",
    color: "Negro",
    price: 5200,
    stock: 1,
  },
  {
    id: 13,
    name: "Ojotas",
    alt: "Foto de calzado",
    img: "/Ojota14.jpeg",
    color: "Rosa",
    price: 5200,
    stock: 1,
  },
  {
    id: 14,
    name: "Ojotas",
    alt: "Foto de calzado",
    img: ["/Ojota15.jpeg", "/Ojota19.jpeg", "/Ojota33.jpeg"],
    color: "Gris",
    price: 7900,
    stock: 1,
  },
  {
    id: 15,
    name: "Ojotas",
    alt: "Foto de calzado",
    img: "/Ojota16.jpeg",
    color: "Blanco",
    price: 5200,
    stock: 1,
  },
  {
    id: 16,
    name: "Ojotas",
    alt: "Foto de calzado",
    img: "/Ojota17.jpeg",
    color: "Negro",
    price: 5200,
    stock: 1,
  },
  {
    id: 17,
    name: "Ojotas",
    alt: "Foto de calzado",
    img: "/Ojota18.jpeg",
    color: "Negro",
    price: 5200,
    stock: 1,
  },
  {
    id: 18,
    name: "Ojotas",
    alt: "Foto de calzado",
    img: "/Ojota20.jpeg",
    color: "Violeta oscuro",
    price: 7900,
    stock: 1,
  },
  {
    id: 19,
    name: "Ojotas",
    alt: "Foto de calzado",
    img: "/Ojota21.jpeg",
    color: "Violeta claro",
    price: 5200,
    stock: 1
  },
  {
    id: 20,
    name: "Ojotas",
    alt: "Foto de calzado",
    img: "/Ojota22.jpeg",
    color: "Blanco",
    price: 5200,
    stock: 1,
  },
  {
    id: 21,
    name: "Ojotas",
    alt: "Foto de calzado",
    img: "/Ojota23.jpeg",
    color: "Verde oscuro",
    price: 5200,
    stock: 1,
  },
  {
    id: 22,
    name: "Ojotas",
    alt: "Foto de calzado",
    img: "/Ojota24.jpeg",
    color: "Verde claro",
    price: 5200,
    stock: 1,
  },
  {
    id: 23,
    name: "Ojotas",
    alt: "Foto de calzado",
    img: "/Ojota25.jpeg",
    color: "Violeta",
    price: 7900,
    stock: 1,
  },
  {
    id: 24,
    name: "Ojotas",
    alt: "Foto de calzado",
    img: "/Ojota26.jpeg",
    color: "Rojo",
    price: 5200,
    stock: 1,
  },
  {
    id: 25,
    name: "Ojotas",
    alt: "Foto de calzado",
    img: "/Ojota27.jpeg",
    color: "Blanco",
    price: 7900,
    stock: 1,
  },
  {
    id: 26,
    name: "Ojotas",
    alt: "Foto de calzado",
    img: "/Ojota28.jpeg",
    color: "Blanco",
    price: 7900,
    stock: 1,
  },
  {
    id: 27,
    name: "Ojotas",
    alt: "Foto de calzado",
    img: "/Ojota29.jpeg",
    color: "Blanco",
    price: 7900,
    stock: 1,
  },
  {
    id: 28,
    name: "Ojotas",
    alt: "Foto de calzado",
    img: "/Ojota30.jpeg",
    color: "Violeta",
    price: 5200,
    stock: 1,
  },
  {
    id: 29,
    name: "Ojotas",
    alt: "Foto de calzado",
    img: "/Ojota31.jpeg",
    color: "Rojo",
    price: 5200,
    stock: 1
  },
  {
    id: 30,
    name: "Ojotas",
    alt: "Foto de calzado",
    img: "/Ojota32.jpeg",
    color: "Amarillo",
    price: 5200,
    stock: 1,
  },
  {
    id: 31,
    name: "Ojotas",
    alt: "Foto de calzado",
    img: "/Ojota34.jpeg",
    color: "Violeta oscuro",
    price: 7900,
    stock: 1,
  },
  {
    id: 32,
    name: "Ojotas",
    alt: "Foto de calzado",
    img: "/Ojota35.jpeg",
    color: "Negro",
    price: 7900,
    stock: 1,
  },
  {
    id: 33,
    name: "Ojotas",
    alt: "Foto de calzado",
    img: "/Ojota36.jpeg",
    color: "Violeta",
    price: 5200,
    stock: 1,
  },
];

export function transformToDinero(numero){
  if(numero < 1000) return `$${numero}`
  if(numero >= 1000 && numero < 10000) return `$${numero.toString()[0]}.${numero.toString().slice(1)}`
  if(numero >= 10000 && numero < 100000) return `$${numero.toString().slice(0 ,2)}.${numero.toString().slice(2)}`
  if(numero >= 100000 && numero < 1000000) return `$${numero.toString().slice(0 ,3)}.${numero.toString().slice(3)}`
}
